(define (problem pb2)
  (:domain blocksworld)
  (:objects b1 b2 b3)
  (:init (clear b1) (clear b2) (clear b3) (on-table b1) (on-table b2) (on-table b3) (arm-empty))
  (:goal (and (on b1 b2) (on b2 b3)))
)
