(define (problem pb3)
  (:domain blocksworld)
  (:objects b1 b2 b3 b4)
  (:init (clear b1) (clear b2) (clear b3) (clear b4) (on-table b1) (on-table b2) (on-table b3) (on-table b4) (arm-empty))
  (:goal (and (on b3 b4) (on-table b1) (on-table b2)))
)
